INSERT INTO CODE_LIST (ID, SOURCE, NAME, VALUE, ICON) values (37, 'APP', 'findingOtherEvidence', 'Urine', '');

DELETE FROM SQLITE_SEQUENCE WHERE NAME = 'CODE_LIST';
INSERT INTO SQLITE_SEQUENCE (NAME, SEQ) VALUES ('CODE_LIST', 37);